//
// Created by thomas on 19.05.24.
//

/*
 * LOG_LEVELs: NONE, ERR, WARN, INFO, DBG
 */

#ifndef CONTIKI_NG_PROJEKTMODUL_PROJECT_CONF_H
#define CONTIKI_NG_PROJEKTMODUL_PROJECT_CONF_H

#endif //CONTIKI_NG_PROJEKTMODUL_PROJECT_CONF_H

#define LOG_CONF_LEVEL_MAC  LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_6TOP LOG_LEVEL_NONE
